# frozen_string_literal: true

source "https://rubygems.org"

gemspec

gem "groundwork-forms_core",            path: "../forms_core"
gem "groundwork-forms_rails",           path: "../forms_rails"
gem "groundwork-rules_engine",          path: "../rules_engine"
gem "groundwork-government_attributes", path: "../government_attributes"

group :development, :test do
  gem "rspec-rails",        "~> 7.0"
  gem "factory_bot_rails"
  gem "sqlite3",            "~> 2.0"
end
