# frozen_string_literal: true
# config/initializers/groundwork.rb
#
# Configure Groundwork CaseManagement.
# This file is generated by `bin/rails generate groundwork:install`.

# RailsEventStore is configured automatically by the Groundwork engine.
# Override here if you need custom middleware, repositories, or dispatcher options:
#
# Rails.configuration.event_store = RailsEventStore::Client.new(
#   repository: RubyEventStore::InMemoryRepository.new  # useful for tests
# )

# Register WorkflowRouter subclasses so they subscribe to events on boot.
# Uncomment and add your routers as you generate them:
#
# PermitWorkflowRouter.register!
